"""rag2.0

Revision ID: 5b911eba7950
Revises: e8cd253c8c4e
Create Date: 2026-04-21 09:27:02.582261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b911eba7950'
down_revision: Union[str, Sequence[str], None] = 'e8cd253c8c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.add_column('detecciones', sa.Column('cultivo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'detecciones', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    op.add_column('estacion', sa.Column('cultivo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'estacion', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    op.add_column('recomendaciones', sa.Column('cultivo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recomendaciones', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_column('recomendaciones', 'cultivo_id')
    op.drop_constraint(None, 'estacion', type_='foreignkey')
    op.drop_column('estacion', 'cultivo_id')
    op.drop_constraint(None, 'detecciones', type_='foreignkey')
    op.drop_column('detecciones', 'cultivo_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
