"""Create users table

Revision ID: d5e7a0005744
Revises: 
Create Date: 2026-04-20 23:01:07.848596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e7a0005744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cultivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultivo_id'), 'cultivo', ['id'], unique=False)
    op.create_index(op.f('ix_cultivo_nombre'), 'cultivo', ['nombre'], unique=False)
    op.create_index(op.f('ix_cultivo_tipo'), 'cultivo', ['tipo'], unique=False)
    op.create_index(op.f('ix_cultivo_ubicacion'), 'cultivo', ['ubicacion'], unique=False)
    op.create_table('detecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('cultivo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detecciones_id'), 'detecciones', ['id'], unique=False)
    op.create_index(op.f('ix_detecciones_nombre'), 'detecciones', ['nombre'], unique=False)
    op.create_table('estacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('cultivo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estacion_id'), 'estacion', ['id'], unique=False)
    op.create_index(op.f('ix_estacion_nombre'), 'estacion', ['nombre'], unique=False)
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=True),
    sa.Column('respuestas', sa.Text(), nullable=True),
    sa.Column('cultivo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    op.create_index(op.f('ix_recomendaciones_pregunta'), 'recomendaciones', ['pregunta'], unique=False)
    op.create_index(op.f('ix_recomendaciones_respuestas'), 'recomendaciones', ['respuestas'], unique=False)
    op.create_table('lectura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.FLOAT(), nullable=False),
    sa.Column('humedad', sa.FLOAT(), nullable=False),
    sa.Column('Ph', sa.FLOAT(), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectura_id'), 'lectura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectura_id'), table_name='lectura')
    op.drop_table('lectura')
    op.drop_index(op.f('ix_recomendaciones_respuestas'), table_name='recomendaciones')
    op.drop_index(op.f('ix_recomendaciones_pregunta'), table_name='recomendaciones')
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.drop_table('recomendaciones')
    op.drop_index(op.f('ix_estacion_nombre'), table_name='estacion')
    op.drop_index(op.f('ix_estacion_id'), table_name='estacion')
    op.drop_table('estacion')
    op.drop_index(op.f('ix_detecciones_nombre'), table_name='detecciones')
    op.drop_index(op.f('ix_detecciones_id'), table_name='detecciones')
    op.drop_table('detecciones')
    op.drop_index(op.f('ix_cultivo_ubicacion'), table_name='cultivo')
    op.drop_index(op.f('ix_cultivo_tipo'), table_name='cultivo')
    op.drop_index(op.f('ix_cultivo_nombre'), table_name='cultivo')
    op.drop_index(op.f('ix_cultivo_id'), table_name='cultivo')
    op.drop_table('cultivo')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
