"""rag1

Revision ID: e8cd253c8c4e
Revises: d5e7a0005744
Create Date: 2026-04-21 09:26:01.632568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cd253c8c4e'
down_revision: Union[str, Sequence[str], None] = 'd5e7a0005744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cultivo_usuario_id_fkey'), 'cultivo', type_='foreignkey')
    op.drop_column('cultivo', 'usuario_id')
    op.drop_constraint(op.f('detecciones_cultivo_id_fkey'), 'detecciones', type_='foreignkey')
    op.drop_column('detecciones', 'cultivo_id')
    op.drop_constraint(op.f('estacion_cultivo_id_fkey'), 'estacion', type_='foreignkey')
    op.drop_column('estacion', 'cultivo_id')
    op.drop_constraint(op.f('recomendaciones_cultivo_id_fkey'), 'recomendaciones', type_='foreignkey')
    op.drop_column('recomendaciones', 'cultivo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recomendaciones', sa.Column('cultivo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('recomendaciones_cultivo_id_fkey'), 'recomendaciones', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    op.add_column('estacion', sa.Column('cultivo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('estacion_cultivo_id_fkey'), 'estacion', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    op.add_column('detecciones', sa.Column('cultivo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('detecciones_cultivo_id_fkey'), 'detecciones', 'cultivo', ['cultivo_id'], ['id'], ondelete='CASCADE')
    op.add_column('cultivo', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cultivo_usuario_id_fkey'), 'cultivo', 'users', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
